pypy: we require pypy-2.6.0
to prevent this error:

Error in HTTPServer.tick
Traceback (most recent call last):
  File "/home/travis/virtualenv/pypy-2.5.0/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 1968, in start
    self.tick()
  File "/home/travis/virtualenv/pypy-2.5.0/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 2059, in tick
    conn = self.ConnectionClass(self, s, makefile)
  File "/home/travis/virtualenv/pypy-2.5.0/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 1327, in __init__
    self.rfile = makefile(sock, "rb", self.rbufsize)
  File "/home/travis/virtualenv/pypy-2.5.0/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 1004, in __init__
    socket._fileobject.__init__(self, *args, **kwargs)
  File "/opt/python/pypy-2.5.0/lib-python/2.7/socket.py", line 300, in __init__
    sock._reuse()
AttributeError: '_socketobject' object has no attribute '_reuse'